kind: Service
apiVersion: v1
metadata:
  name:  {{ include "caesar-server.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "caesar-server.fullname" . }}
    helm.sh/chart: {{ include "caesar-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name:  {{include "caesar-server.fullname" . }}
  type:  NodePort
  ports:
    - name:  http
      port:  80
      targetPort:  80
    - name:  php-fpm
      port:  9000
      targetPort:  9000