apiVersion: apps/v1
kind: Deployment
metadata:
  name: caesar-server
  namespace: {{ .Values.namespace}}
  labels:
    app.kubernetes.io/name: {{include "caesar.name" . }}
    helm.sh/chart: {{include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/managed-by: {{ .Release.Service}}
    keel.sh/policy: all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caesar-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      namespace: {{ .Values.namespace}}
      labels:
        app.kubernetes.io/name: {{include "caesar.name" . }}
        helm.sh/chart: {{include "caesar.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name}}
        app.kubernetes.io/managed-by: {{ .Release.Service}}
        keel.sh/policy: all
        app: caesar-server
    spec:
      containers:
        - name: caesar-server
          image: "caesarteam/caesar-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: caesar-server-config
            - secretRef:
                name: caesar-server-secret
            - configMapRef:
                name: mailer-config
          ports:
            - name: php-fpm
              containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/html/public
              name: caesar-static-files
            - mountPath: /var/www/html/var/jwt
              name: caesar-certificate
        - name: nginx
          image: "nginx:alpine"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config-volume
              subPath: nginx.conf
            - mountPath: /var/www/html/public
              name: caesar-static-files
      initContainers:
        - name: copy-public
          image: "caesarteam/caesar-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy | quote }}
          command: ["/bin/cp", "-r", "public/.", "public_site/"]
          volumeMounts:
            - mountPath: /var/www/html/public_site
              name: caesar-static-files
      securityContext:
        runAsUser: 82
        runAsGroup: 82
        fsGroup: 82
      volumes:
        - name: caesar-certificate
          persistentVolumeClaim:
            claimName: caesar-certificate
        - name: caesar-static-files
          persistentVolumeClaim:
            claimName: caesar-static-files
        - configMap:
            defaultMode: 256
            name: nginx-config
            optional: false
          name: nginx-config-volume
