apiVersion: v1
entries:
  backuper:
  - apiVersion: v2
    appVersion: "2.0"
    created: "2020-12-08T22:25:56.9059044+03:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 4.1.1
    description: The backuper is a container image based on Alpine Linux
    digest: 22e548b660905af02e30882d65563d021701a6920ee9ea61dc624f14a6e521c3
    home: https://github.com/caesar-team/helm-charts/tree/master/stable/backuper
    icon: https://avatars0.githubusercontent.com/u/29732245?s=400&u=ad209da860bf9b9dd270dc30c76d525af6b468ca&v=4
    keywords:
    - db
    - backup
    - script
    maintainers:
    - email: ave@caesar.team
      name: Caesar
    name: backuper
    sources:
    - https://github.com/caesar-team/helm-charts
    - https://caesar.team
    type: application
    urls:
    - backuper-2.tgz
    version: "2"
  minio:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 2020.12.3
    created: "2020-12-08T22:25:56.9072491+03:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: MinIO is an object storage server, compatible with Amazon S3 cloud
      storage service, mainly used for storing unstructured data (such as photos,
      videos, log files, etc.)
    digest: 692c53a95706873718f6e0335fd92d97eafeeec9a69e4a727b43144fdba7825b
    home: https://github.com/bitnami/charts/tree/master/bitnami/minio
    icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: minio
    sources:
    - https://github.com/bitnami/bitnami-docker-minio
    - https://min.io
    urls:
    - charts/minio-4.1.1.tgz
    version: 4.1.1
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2020-12-08T22:25:56.9103859+03:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2020-12-08T22:25:56.9009553+03:00"
