apiVersion: v1
kind: Secret
metadata:
metadata:
  name: {{ .Values.postgres.name | quote }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.postgresDB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.postgresUser | b64enc | quote }}
  {{- if .Values.postgres.postgresPassword }}
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresPassword | b64enc | quote }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}