{{ if .Values.mailer.enable }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "caesar-server.fullname" . }}-mailer-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "caesar-server.fullname" . }}
    helm.sh/chart: {{ include "caesar-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  mailer_dsn: {{ required "A valid .Values.mailer.secret.mailer_dsn entry required!" .Values.mailer.secret.mailer_dsn | b64enc | quote }}
type: Opaque
{{ end }}