apiVersion: v2
appVersion: "2.0"
description: "This is a server for the Caesar.Team a password manager for teams"
home: https://github.com/caesar-team/helm-charts/tree/master/charts/stable/caesar-server
icon: https://avatars0.githubusercontent.com/u/29732245?s=400&u=ad209da860bf9b9dd270dc30c76d525af6b468ca&v=4
name: caesar-server
version: "2.0"
type: application
keywords:
  - application
  - password
  - manager
  - team
  - php
  - symfony
maintainers:
  - email: ave@caesar.team
    name: Caesar
sources:
  - https://github.com/caesar-team/helm-charts
  - https://caesar.team

configureRepositories:
  enable: true
  repositories:
    - name: https://charts.bitnami.com/bitnami
      url: https://charts.bitnami.com/bitnami

dependencies:
  - name: postgresql
    version: 10.1.1
    repository: https://charts.bitnami.com/bitnami
  - condition: redis.enabled
    name: redis
    version: 12.1.1
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 8.2.0
    repository: https://charts.bitnami.com/bitnami
