apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "caesar-web-client.fullname" . }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "caesar-web-client.fullname" . }}
    helm.sh/chart: {{ include "caesar-web-client.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ default "50MB" .Values.ingress.annotations.body_size | quote }}
    nginx.org/client-max-body-size: {{ default "50MB" .Values.ingress.annotations.body_size | quote }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName:  {{ include "caesar-web-client.fullname" . }}-headless
          servicePort: 3000
  tls:
  - hosts:
    - {{ .Values.domain }}