apiVersion: apps/v1
kind: Deployment
metadata:
  name: caesar-server-email-consumer
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caesar-server-email-consumer
  template:
    metadata:
      labels:
        app: caesar-server-email-consumer
    spec:
      containers:
        - name: caesar-server-email-consumer
          image: "caesarteam/caesar-server-email-consumer:{{ .Values.consumer.branch }}"
          envFrom:
            - configMapRef:
                name: rabbitmq-config  
            - configMapRef:
                name: caesar-server-config
            - configMapRef:
                name: email-consumer-config    
            - secretRef:
                name: email-consumer-secret    
            - secretRef:
                name: rabbitmq-secret  
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always