# Default values for caesar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
namespace: ""
domain: &default_domain default.caesar.team
app_name: "Default Caesar Team"
sender_address: "no-reply@*default_domain"

global:
  #   imageRegistry: myRegistryName
  #   imagePullSecrets:
  #     - myRegistryKeySecretName
  storageClass: "hostpath"

image:
  registry: docker.io
  repository: caesarteam/caesar-web-client
  tag: master
  # pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName
  ## Set to true if you would like to see extra information on logs
  ##
  debug: false

ingress:
  annotations:
    body_size: 50m

app:
  config:
    api_base_path: "api"
    app_type: "general"
    api_uri: "*default_domain"
    app_uri: "*default_domain"
    auth_endpoint: "connect/google"
    authorization_enable: "true"
    is_extension: "false"
    length_key: "2048"
    max_size_random_buffer: "60000"
    node_env: "production"
    max_uploading_file_size: "5mb"
    total_max_uploading_files_sizes: "20mb"
