apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caesarappServer.name | quote }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ALLOW_FRONT_REDIRECT_PATTERN: {{ .Values.caesarappServer.allowFrontRedirectPattern | b64enc | quote }}
  {{- if .Values.caesarappServer.appSecret }}
  APP_SECRET: {{ .Values.caesarappServer.appSecret | b64enc | quote }}
  {{- else }}
  APP_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  DATABASE_URL: {{ .Values.caesarappServer.dataBaseUrl | b64enc | quote }}
  BACKUP_CODE_HASH_LENGTH: {{ .Values.caesarappServer.backupCodeHashLength | b64enc | quote }}
  BACKUP_CODE_SALT: {{ .Values.caesarappServer.backupCodeSalt | b64enc | quote }}
  GOOGLE_ID: {{ .Values.caesarappServer.googleID | b64enc | quote }}
  GOOGLE_SECRET: {{ .Values.caesarappServer.googleSecret | b64enc | quote }}
  {{- if .Values.caesarappServer.jwtPassPhrase }}
  JWT_PASSPHRASE: {{ .Values.caesarappServer.jwtPassPhrase | b64enc | quote }}
  {{- else }}
  JWT_PASSPHRASE: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  MAILER_URL: {{ .Values.caesarappServer.mailerUrl | b64enc | quote }}
  OAUTH_ALLOWED_DOMAINS: {{ .Values.caesarappServer.oauthAllowedDomain | b64enc | quote }}
  SENDER_ADDRESS: {{ .Values.caesarappServer.senderAddress | b64enc | quote }}
  SUPERADMIN_PASS: JDJ5JDEzJFM4SU0xbkJoOExveTRqN2lmejZjN3VDTVBteDdSMVZvbC5oRS9Nai41SUZCam9SWktLY1I2
  TWO_FACTOR_SERVER_NAME: {{ .Values.caesarappServer.twoFactorServerName | b64enc | quote }}