apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caesar-shared-static
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage