apiVersion: v1
kind: Secret
data:
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque