apiVersion: v1
kind: Service
metadata:
  name:  redis
spec:
  selector:
    app:  redis
  type:  NodePort
  ports:
    - name:  redis-port
      port:  {{ default "6379" .Values.redis.config.port }} 
      targetPort:  {{ default "6379" .Values.redis.config.port }} 