apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: redis
data:
  REDIS_HOST: {{ default "redis" .Values.redis.config.host }}
  REDIS_PORT: {{ default "6379" .Values.redis.config.port | quote }} 