apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  REDIS_HOST: {{ default "redis" .Values.redis.config.host }}
  REDIS_PORT: {{ default "6379" .Values.redis.config.port | quote }} 