apiVersion: v1
kind: Service
metadata:
  name:  redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: redis
spec:
  selector:
    app:  redis
  type:  NodePort
  ports:
    - name:  redis-port
      port:  {{ default "6379" .Values.redis.config.port }} 
      targetPort:  {{ default "6379" .Values.redis.config.port }} 