{{ if .Values.backuper.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: backuper-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret.aws_secret_access_key | b64enc | quote }}
  ENCRYPT_PASS: {{ .Values.backuper.secret.encrypt_pass | b64enc | quote }}
type: Opaque
{{ end }}