apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ## Here are the test data! Use your real username and password
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.secret.rabbitmq_default_pass | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.secret.rabbitmq_default_user | b64enc | quote }}
type: Opaque