apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name:  rabbitmq
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type:  NodePort
  selector:
    app:  rabbitmq
  ports:
    - name:  rabbitmq-port
      port:  {{ default "5672" .Values.rabbitmq.config.port }} 
      targetPort:  {{ default "5672" .Values.rabbitmq.config.port }}       