apiVersion: v1
kind: Service
metadata:
  name:  postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app:  postgres
  type:  NodePort
  ports:
    - name:  postgres-port
      port:  5432
      targetPort:  5432