apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backuper.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{include "backuper.fullname" . }}
    helm.sh/chart: {{include "backuper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/managed-by: {{ .Release.Service}}
spec:
data:
  AWS_SECRET_ACCESS_KEY: {{ required "A valid .Values.aws.secret_access_key entry required!" .Values.aws.secret_access_key | b64enc | quote }}
  ENCRYPT_PASS: {{ required "A valid .Values.secret.encrypt_pass entry required!" .Values.secret.encrypt_pass | b64enc | quote }}
  DB_PASSWORD: {{  required "A valid .Values.postgresql.postgresqlPassword entry required!" .Values.postgresql.postgresqlPassword | b64enc | quote }}
type: Opaque
