---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backuper.fullname" . }}-cronjob
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{include "backuper.fullname" . }}
    helm.sh/chart: {{include "backuper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/managed-by: {{ .Release.Service}}
spec:
  schedule: '0 01 * * *'
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-message-history
            image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
            command: ["/bin/sh"]
            args: ["/pgsql-backup.sh"]
            envFrom:
            - secretRef:
                name: {{ include "backuper.fullname" . }}-secret
                optional: false
            - configMapRef:
                name: {{ include "backuper.fullname" . }}-config
                optional: false
          restartPolicy: OnFailure
