{{ if .Values.mailer.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: mailer-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "caesar.name" . }}
    helm.sh/chart: {{ include "caesar.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  mailer_dsn: {{ required "A valid .Values.mailer.secret.mailer_dsn entry required!" .Values.mailer.secret.mailer_dsn | b64enc | quote }}
type: Opaque
{{ end }}