name: Build chart on the tag action

on:
  push:
    tags:
    - '*'
    
name: Publish Helm chart
jobs:
  helmGh-pages:
    name: Helm gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Helm gh-pages
      uses: stefanprodan/gh-actions/helm-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: caesar https://caesar-team.github.io/caesar
